spring:
  application:
    name: palantir
  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    io.github.jakubt4.palantir: DEBUG

yamcs:
  udp:
    host: ${YAMCS_UDP_HOST:localhost}
    port: ${YAMCS_UDP_PORT:10000}
